// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAIS.Models.Data;

#nullable disable

namespace SAIS.Migrations
{
    [DbContext(typeof(SAISDbContext))]
    partial class SAISDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAIS.Models.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("ApplicantId");

                    b.HasIndex("GenderId");

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("VillageId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("SAIS.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicantSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfficerSignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("OfficerId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SAIS.Models.AppliedProgram", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("AppliedProgramId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("AppliedPrograms");
                });

            modelBuilder.Entity("SAIS.Models.County", b =>
                {
                    b.Property<int>("CountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountyId"));

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountyId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            CountyId = 1,
                            CountyName = "Nairobi"
                        });
                });

            modelBuilder.Entity("SAIS.Models.GenderCategory", b =>
                {
                    b.Property<int>("GenderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderCategoryId"));

                    b.Property<string>("GenderCategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GenderCategoryId");

                    b.ToTable("GenderCategories");

                    b.HasData(
                        new
                        {
                            GenderCategoryId = 1,
                            GenderCategoryName = "Male"
                        },
                        new
                        {
                            GenderCategoryId = 2,
                            GenderCategoryName = "Female"
                        });
                });

            modelBuilder.Entity("SAIS.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubCountyId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex("SubCountyId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Kitisuru",
                            SubCountyId = 1
                        });
                });

            modelBuilder.Entity("SAIS.Models.MaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaritalStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaritalStatusId");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            MaritalStatusId = 1,
                            StatusName = "Single"
                        },
                        new
                        {
                            MaritalStatusId = 2,
                            StatusName = "Married"
                        },
                        new
                        {
                            MaritalStatusId = 3,
                            StatusName = "Divorced"
                        },
                        new
                        {
                            MaritalStatusId = 4,
                            StatusName = "Widowed"
                        });
                });

            modelBuilder.Entity("SAIS.Models.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OfficerId");

                    b.ToTable("Officers");

                    b.HasData(
                        new
                        {
                            OfficerId = 1,
                            Designation = "Social Worker",
                            OfficerName = "John Mwangi"
                        });
                });

            modelBuilder.Entity("SAIS.Models.PhoneNumber", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhoneId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("SAIS.Models.SocialAssistanceProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProgramId");

                    b.ToTable("SocialAssistancePrograms");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            ProgramName = "Orphans & Vulnerable"
                        },
                        new
                        {
                            ProgramId = 2,
                            ProgramName = "Elderly Persons"
                        },
                        new
                        {
                            ProgramId = 3,
                            ProgramName = "Disability"
                        },
                        new
                        {
                            ProgramId = 4,
                            ProgramName = "Extreme Poverty"
                        },
                        new
                        {
                            ProgramId = 5,
                            ProgramName = "Other"
                        });
                });

            modelBuilder.Entity("SAIS.Models.SubCounty", b =>
                {
                    b.Property<int>("SubCountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCountyId"));

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("SubCountyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCountyId");

                    b.HasIndex("CountyId");

                    b.ToTable("SubCounties");

                    b.HasData(
                        new
                        {
                            SubCountyId = 1,
                            CountyId = 1,
                            SubCountyName = "Westlands"
                        });
                });

            modelBuilder.Entity("SAIS.Models.SubLocation", b =>
                {
                    b.Property<int>("SubLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubLocationId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("SubLocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubLocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("SubLocations");

                    b.HasData(
                        new
                        {
                            SubLocationId = 1,
                            LocationId = 1,
                            SubLocationName = "Kitisuru Estate"
                        });
                });

            modelBuilder.Entity("SAIS.Models.Village", b =>
                {
                    b.Property<int>("VillageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillageId"));

                    b.Property<int>("SubLocationId")
                        .HasColumnType("int");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VillageId");

                    b.HasIndex("SubLocationId");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            VillageId = 1,
                            SubLocationId = 1,
                            VillageName = "Kitisuru Village"
                        });
                });

            modelBuilder.Entity("SAIS.Models.Applicant", b =>
                {
                    b.HasOne("SAIS.Models.GenderCategory", "GenderCategory")
                        .WithMany("Applicants")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAIS.Models.MaritalStatus", "MaritalStatus")
                        .WithMany("Applicants")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAIS.Models.Village", "Village")
                        .WithMany("Applicants")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenderCategory");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("SAIS.Models.Application", b =>
                {
                    b.HasOne("SAIS.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAIS.Models.Officer", "Officer")
                        .WithMany("Applications")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("SAIS.Models.AppliedProgram", b =>
                {
                    b.HasOne("SAIS.Models.Application", "Application")
                        .WithMany("AppliedPrograms")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAIS.Models.SocialAssistanceProgram", "SocialAssistanceProgram")
                        .WithMany("AppliedPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("SocialAssistanceProgram");
                });

            modelBuilder.Entity("SAIS.Models.Location", b =>
                {
                    b.HasOne("SAIS.Models.SubCounty", "SubCounty")
                        .WithMany("Locations")
                        .HasForeignKey("SubCountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCounty");
                });

            modelBuilder.Entity("SAIS.Models.PhoneNumber", b =>
                {
                    b.HasOne("SAIS.Models.Applicant", "Applicant")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("SAIS.Models.SubCounty", b =>
                {
                    b.HasOne("SAIS.Models.County", "County")
                        .WithMany("SubCounties")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("SAIS.Models.SubLocation", b =>
                {
                    b.HasOne("SAIS.Models.Location", "Location")
                        .WithMany("SubLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SAIS.Models.Village", b =>
                {
                    b.HasOne("SAIS.Models.SubLocation", "SubLocation")
                        .WithMany("Villages")
                        .HasForeignKey("SubLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubLocation");
                });

            modelBuilder.Entity("SAIS.Models.Applicant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("SAIS.Models.Application", b =>
                {
                    b.Navigation("AppliedPrograms");
                });

            modelBuilder.Entity("SAIS.Models.County", b =>
                {
                    b.Navigation("SubCounties");
                });

            modelBuilder.Entity("SAIS.Models.GenderCategory", b =>
                {
                    b.Navigation("Applicants");
                });

            modelBuilder.Entity("SAIS.Models.Location", b =>
                {
                    b.Navigation("SubLocations");
                });

            modelBuilder.Entity("SAIS.Models.MaritalStatus", b =>
                {
                    b.Navigation("Applicants");
                });

            modelBuilder.Entity("SAIS.Models.Officer", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SAIS.Models.SocialAssistanceProgram", b =>
                {
                    b.Navigation("AppliedPrograms");
                });

            modelBuilder.Entity("SAIS.Models.SubCounty", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SAIS.Models.SubLocation", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("SAIS.Models.Village", b =>
                {
                    b.Navigation("Applicants");
                });
#pragma warning restore 612, 618
        }
    }
}
